 pipeline {
    agent any

  environment {
        // 환경 변수를 정의
        CLASSPATH = "classes;lib/;path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
    }
  
    stages {
        stage('Checkout') {
            steps {
                // 소스코드 체크아웃
                checkout scm
            }
        }
        stage('Build') {
          steps {
              bat 'javac -encoding UTF-8 -d classes Software_ex/src/*.java'
          }
      }
      stage('Test') {
          steps {
           scripts {
              def classpath = "classes;lib/;path/to/eclipse/plugins/junit-platform-console-standalone-1.7.1.jar"
              bat 'java -cp classes;lib/;path/to/eclipse/plugins/junitplatform-console-standalone-1.7.1.jar org.junit.platform.console.ConsoleLauncher--scan-classpath> test_results.txt'
           }
         
           
          }
         }
      }
   post {
           always {
               // 테스트 결과 파일을 저장하기 위해 아카이브
               archiveArtifacts 'test_results.txt'
           }
           failure {
               echo 'Build or test failed'
           }
           success {
               echo 'Build and test succeeded'
           }
       }
 }
